language: rust
matrix:
    fast_finish: true
    include:
        - rust: nightly
          sudo: false
        - rust: beta
          sudo: false
        - rust: stable
          sudo: false

cache:
    directories:
        - target
        - $HOME/bin
        - $HOME/kcov

script: ./.travis.sh

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    bash .travis.install_kcov.sh &&
    $HOME/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/maillog-*

notifications:
    email: false
