language: rust
matrix:
    fast_finish: true
    include:
        - rust: nightly
          sudo: false
        - rust: beta
          sudo: false
        - rust: stable
          sudo: true

cache:
    directories:
        - target

script: ./.travis.sh

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
    wget https://github.com/Feandil/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
    sudo make install && cd ../.. &&
    kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/maillog-*

notifications:
    email: false
